### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by haesleinhuepf** [jpylvanainen/Image_analysis_course_24#1]
Hi @jpylvanainen ,

that's a fantastic repository! Thanks for sharing these materials openly! I was just wondering under which conditions one could reuse the code and materials provided here, e.g. for other courses. Would you mind adding a license file? If you're new to licensing and/or wonder which license to use, you can read more in this blob post: https://focalplane.biologists.com/2023/05/06/if-you-license-it-itll-be-harder-to-steal-it-why-we-should-license-our-work/

Thanks!

Best,
Robert

**Comment by jpylvanainen** [comment]
Thanks @haesleinhuepf thanks for the reminder! This was not forgotten, just didn't get around it yet!

**Comment by jpylvanainen** [comment]
License added!

**Comment by haesleinhuepf** [comment]
Fantastic, thanks!
